-   id: check-docstrings
    name: Check docstrings
    description: This hook checks if methods longer than a certain length have docstrings.
    entry: check-docstrings
    language: python
    types: [python]